package org.fireking.uudownload.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.fireking.uudownload.DownloadRequest;

import org.fireking.uudownload.greendao.DownloadRequestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadRequestDaoConfig;

    private final DownloadRequestDao downloadRequestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadRequestDaoConfig = daoConfigMap.get(DownloadRequestDao.class).clone();
        downloadRequestDaoConfig.initIdentityScope(type);

        downloadRequestDao = new DownloadRequestDao(downloadRequestDaoConfig, this);

        registerDao(DownloadRequest.class, downloadRequestDao);
    }
    
    public void clear() {
        downloadRequestDaoConfig.clearIdentityScope();
    }

    public DownloadRequestDao getDownloadRequestDao() {
        return downloadRequestDao;
    }

}
